In [4]:
![image.png](attachment:image.png)

zsh:1: number expected

## PRACTICA OBLIGATORIA: **Estadistica Inferencial y Probabilidad**

* La práctica obligatoria de esta unidad consiste en un único ejercicio de construcción de gráficas. Descarga este notebook en tu ordenador y trabaja en local. Ten en cuenta que tendrás que descar los directorios de imágenes y datos adicionales, si los hubiera.
* Recuerda que debes subirla a tu repositorio personal antes de la sesión en vivo para que puntúe adecuadamente.  
* Recuerda también que no es necesario que esté perfecta, sólo es necesario que se vea el esfuerzo. 
* Esta práctica se resolverá en la sesión en vivo correspondiente y la solución se publicará en el repo del curso.

### Ejercicio 0

Importa los paquetes y módulos que necesites a lo largo del notebook.

In [18]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

## #1 Titanic

Carga el dataset del titanic, y contesta a las siguientes preguntas:

1. ¿Cuál es la probabilidad de superviviencia de un niño?
2. ¿Cuál es la probabilidad de que una mujer viajase sola?
3. ¿Cuál es la probabilidad de sobreviviese un hombre entre 30 y 40 años que embarcó en Southampton y no tuvo que pagar billete?
4. ¿Y si hubiera acompañado de 2 familiares?
5. Si consideramos ahora que queremos tener cierta confianza estadística en nuestras probabilidades (ten en cuenta que estamos extrapolando los ratios de una muestra), ¿cuál sería el rango de probabilidades de sobrevivir de una persona que viajase sola al 95%?
6. EXTRA: ¿Y si además el pasajero de 5 fuera un pasajero de tercera o de segunda?

In [2]:
# Carga del dataset
df_titanic = pd.read_csv("./data/titanic.csv")

In [7]:
# Analizamos el dataset
df_titanic.head()

,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone
0,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False
1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False
2,female,26.0,0,0,7.9250,Third,woman,False,Southampton,yes,True
3,female,35.0,1,0,53.1000,First,woman,False,Southampton,yes,False
4,male,35.0,0,0,8.0500,Third,man,True,Southampton,no,True

In [5]:
# 1. ¿Cuál es la probabilidad de superviviencia de un niño?
prob_niño = df_titanic[df_titanic["who"] == "child"]["alive"].value_counts(normalize = True).get("yes", 0)
print(f"La probabilidad de supervivencia de un niño es: {prob_niño:.4f} ({prob_niño*100:.2f}%)")

La probabilidad de supervivencia de un niño es: 0.5904 (59.04%)

In [9]:
# 2. ¿Cuál es la probabilidad de que una mujer viajase sola?
mujeres_titanic = df_titanic[df_titanic["sex"] == "female"]
prob_mujer_sola = (mujeres_titanic["alone"] == True).mean()
print(f"La probabilidad de que una mujer viajase sola: {prob_mujer_sola:.4f} ({prob_mujer_sola*100:.2f}%)")

La probabilidad de que una mujer viajase sola: 0.4013 (40.13%)

In [15]:
# 3. ¿Cuál es la probabilidad de sobreviviese un hombre entre 30 y 40 años que embarcó en Southampton y no tuvo que pagar billete?
filtro_hombre = (
    (df_titanic["sex"] == "male") & 
    (df_titanic["age"] >= 30) & (df_titanic["age"] <= 40) & 
    (df_titanic["embark_town"] == "Southampton") & 
    (df_titanic["fare"] == 0)
)
subconjunto_hombre = df_titanic[filtro_hombre]
if len(subconjunto_hombre) > 0:
    prob_hombre = subconjunto_hombre['alive'].value_counts(normalize=True).get("yes", 0)
else:
    prob_hombre = 0
print(f"La probabilidad de sobrevivir del hombre específico (30-40 años, Southampton, sin pagar) es: {prob_hombre:.10f} (Casos encontrados: {len(subconjunto_hombre)})")

La probabilidad de sobrevivir del hombre específico (30-40 años, Southampton, sin pagar) es: 0.0000000000 (Casos encontrados: 12)

In [16]:
# 4. ¿Y si hubiera acompañado de 2 familiares?
filtro_hombre_2_fam = (
    (df_titanic["sex"] == "male") & 
    (df_titanic["age"] >= 30) & (df_titanic["age"] <= 40) & 
    (df_titanic["embark_town"] == "Southampton") & 
    ((df_titanic["sibsp"] + df_titanic["parch"]) == 2)
)
subconjunto_hombre_2_fam = df_titanic[filtro_hombre_2_fam]
if len(subconjunto_hombre_2_fam) > 0:
    prob_hombre_2_fam = subconjunto_hombre_2_fam['alive'].value_counts(normalize=True).get("yes", 0)
else:
    prob_hombre_2_fam = 0
print(f"La probabilidad de sobrevivir si va con 2 familiares es: {prob_hombre_2_fam:.4f} (Casos encontrados: {len(subconjunto_hombre_2_fam)})")

La probabilidad de sobrevivir si va con 2 familiares es: 0.1250 (Casos encontrados: 8)

In [19]:
# 5. Si consideramos ahora que queremos tener cierta confianza estadística en nuestras probabilidades (ten en cuenta que estamos extrapolando los ratios de una muestra), ¿cuál sería el rango de probabilidades de sobrevivir de una persona que viajase sola al 95%?

In [ ]:
# 6. EXTRA: ¿Y si además el pasajero de 5 fuera un pasajero de tercera o de segunda?

## #2 Life Satisfaction

Carga el dataset de satifacción vital y contesta a las siguietnes preguntas:

1. ¿Podemos asegurar con cierta confianza estadística (del 99%) que la satisfaccion vital media del mundo es menor de 7?
2. ¿Qué nivel de satisfacción media asignaríamos a país con esperanza de vida de más de 65 años y tasa de empleo superior a 60%? (ojo fijate que son umbrales)
3. ¿Cuál sería la probabilidad de tener más de 6 puntos de satisfacción vital para los países con esperanza de vida mayor a 65 años y tasa de empleo superior a 60%?

In [3]:
# Carga del dataset
df_lifesat_full = pd.read_csv("./data/lifesat_full.csv")

In [20]:
# Analizamos el dataset
df_lifesat_full.head()

,Country,GDP per capita (USD),Life satisfaction,Life expectancy,Homicide rate,Employment rate
0,South Africa,11466.189672,4.725336,57.5,13.7,43.0
1,Colombia,13441.492952,6.302556,76.2,24.5,67.0
2,Brazil,14063.982505,6.415187,74.8,26.7,61.0
3,Mexico,17887.750736,6.536861,75.4,18.1,61.0
4,Chile,23324.524751,6.538143,79.9,4.2,63.0

In [24]:
# 1. ¿Podemos asegurar con cierta confianza estadística (del 99%) que la satisfaccion vital media del mundo es menor de 7?
# Revisar en el live review no logro hacerlo

In [21]:
# 2. ¿Qué nivel de satisfacción media asignaríamos a país con esperanza de vida de más de 65 años y tasa de empleo superior a 60%? (ojo fijate que son umbrales)
filtro_umbral = (df_lifesat_full["Life expectancy"] > 65) & (df_lifesat_full["Employment rate"] > 60)
paises_filtrados = df_lifesat_full[filtro_umbral]

satisfaccion_asignada = paises_filtrados["Life satisfaction"].mean()
print(f"\n2. Satisfacción media asignada a estos países: {satisfaccion_asignada:.4f}")

2. Satisfacción media asignada a estos países: 6.7461

In [22]:
# 3. ¿Cuál sería la probabilidad de tener más de 6 puntos de satisfacción vital para los países con esperanza de vida mayor a 65 años y tasa de empleo superior a 60%?
casos_favorables = (paises_filtrados["Life satisfaction"] > 6).sum()
casos_totales = len(paises_filtrados)
prob_mas_6 = casos_favorables / casos_totales

print(f"3. Probabilidad de tener > 6 puntos de satisfacción en este grupo: {prob_mas_6:.4f} ({prob_mas_6*100:.2f}%)")

3. Probabilidad de tener > 6 puntos de satisfacción en este grupo: 0.7812 (78.12%)

## EXTRA: La contrainituividad de la probabilidad

Para poder lidiar con la incertidumbre que nos rodea, **solemos aplicar lo que llamamos nuestro "*sentido común*"**. Por ejemplo, si al levantarnos por la mañana vemos que el día se encuentra nublado, este hecho no nos da la **certeza** de que comenzará a llover más tarde; sin embargo, nuestro *sentido común* puede inducirnos a cambiar nuestros planes y a actuar como si *creyéramos* que fuera a llover si las nubes son los suficientemente oscuras o si escuchamos truenos, ya que nuestra experiencia nos dice que estos signos indicarían una mayor *posibilidad* de que el hecho de que fuera a llover más tarde realmente ocurra. 
Nuestro *sentido común* es algo tan arraigado en nuestro pensamiento, que lo utilizamos automáticamente sin siquiera ponernos a pensar en ello; pero muchas veces, el *sentido común* también nos puede jugar una mala pasada y hacernos elegir una respuesta incorrecta.


#### Situación 1 - La coincidencia de cumpleaños
Vamos a una fiesta a la que concurren un total de 50 personas. Allí un amigo nos desafía afirmando que en la fiesta debe haber por lo menos 2 personas que cumplen años el mismo día y nos apuesta 100 euros a que está en lo correcto. Es decir, que si él acierta deberíamos pagarle los 100 euros; o en caso contrario, el nos pagará los 100 euros. ¿Deberíamos aceptar la apuesta? 


#### Situación 2 - ¿Que puerta elegir? (El dilema de Monty Hall)
Estamos participando en un concurso en el cual se nos ofrece la posibilidad de elegir una entre tres puertas. Tras una de ellas se encuentra una ferrari ultimo modelo, y detrás de las otras dos hay una cabra; luego de elegir una puerta, el presentador del concurso abre una de las puertas restantes y muestra que hay una cabra (el presentador sabe que hay detrás de cada puerta). Luego de hacer esto, el presentador nos ofrece la posibilidad de cambiar nuestra elección inicial y quedarnos con la otra puerta que no habíamos elegido inicialmente. ¿Deberíamos cambiar o confiar en nuestra elección inicial?

¿Qué te diría su *sentido común* que deberían hacer en cada una de estas situaciones?

---

**En la Situación 1** 
Negarme, aun cuando parece loco pensar que no van a coicidir es más que probable decir que si que coinciden al menos dos personas en esa fiesta, el sentido común nos engaña un poco pensando que quiza 50 no son tantas personas, pero aplicando una formula de probabilidad obtenemos que el 97,04% de probabilidades de que si coincidan al menos dos. Pero al final, todo es suerte jeje.

In [23]:
personas_fiesta = 50

# Probabilidad de que todos cumplan años en días DIFERENTES
prob_diferentes = 1.0

for i in range(personas_fiesta):
    prob_diferentes *= (365 - i) / 365

# Probabilidad de coincidencia es el complemento (el resto para llegar a 1)
prob_coincidencia = 1 - prob_diferentes

print(f"Resultados para un grupo de {personas_fiesta} personas:")
print(f"Probabilidad de que todos cumplan días distintos: {prob_diferentes*100:.2f}%")
print(f"Probabilidad de coincidencia (al menos 2 iguales): {prob_coincidencia*100:.2f}%")

Resultados para un grupo de 50 personas:
Probabilidad de que todos cumplan días distintos: 2.96%
Probabilidad de coincidencia (al menos 2 iguales): 97.04%

----
**En la Situación 2**, en este caso, mi sentido común esta condicionado, "nunca cambies la respuesta una vez tomada", por lo wue yo no cambiaría, el sabe la respuesta, por tanto, lo común es pensar que "te está dando una oportunidad", pero quizá solo quiere confundirte plantando la duda porque ya tienes el ferrari 😎